name: Clippy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  stylecheck:
    name: Stylecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain with rustfmt and run cargo format in check mode
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Stable
        run: rustup toolchain install stable --profile=default

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.1

      - name: Run clippy
        run: cargo clippy --features=without-ocamlopt --all -- -D warnings
